### ISSUE TITLE
Sites > Site Info > Validacion de tiempo en las fechas

### ISSUE THREAD

**Issue by ArturooTz** [jorgolo/beanhub#2]
Si no se pone el tiempo junto con la informacion de la fecha (Start, End o Content) , no se guarda nada en la base de datos aunque mande notificacion de Success

**Comment by jorgolo** [comment]
Deberia estar arreglado ya, hacer Qa

**Comment by jorgolo** [comment]
tambien se arreglo en qa_date_fixed
